rabbitmq:
  hostName: "localhost"
  userName: "guest"
  password: "guest"
  port: 5672
  virtualHost: "/"
  useSsl: false
  connectionTimeout: 30000
  requestedHeartbeat: 60
  networkRecoveryInterval: 5000
  queues:
    - name: "queue1"
      exchange: "exchange1"
      routingKey: "routingKey1"
      durable: true
      exclusive: false
      autoDelete: false
      arguments:
        x-message-ttl: 60000 # TTL in milliseconds (integer)
    - name: "queue2"
      exchange: "exchange2"
      routingKey: "routingKey2"
  exchanges:
    - name: "exchange1"
      type: "direct"
      durable: true
      autoDelete: false
  retryConfig:
    maxRetries: 3
    retryInterval: 5000
    deadLetterExchange: "dead_letter_exchange"
    deadLetterQueue: "dead_letter_queue"
  monitoringConfig:
    enableMetrics: true
    metricsEndpoint: "http://metrics.example.com"